<div class="">
    <?php $count = 0 ?>
    <?php foreach ($this->container as $page): ?>
        <?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if( ! $hasChildren): ?>
            <a class="boxlinks-link" href="<?php echo $page->getHref() ?>"><?php echo $this->translate($page->getLabel()) ?></a>
        <?php endif; ?>
        <?php $count++ ?>
    <?php endforeach; ?>
</div>